name: SSH deploy
on: push
jobs:
  deploy:
    name: Deploy project
    runs-on: ubuntu-latest
    steps:
      - name: Get repositor
        uses: actions/checkout@v4
      - name: Deploy
        uses: tiyee/action-ssh@v1.0.1
        with:
          host: ${{ secrets.HOST }}
          port: ${{ secrets.PORT }}
          username: ${{ secrets.USERNAME }}
          privateKey: ${{ secrets.SSH_KEY }}
          command: 'ls -alh'

    




