name: SSH deploying
on: push
jobs:
  deploy:
    name: Deploy project
    runs-on: ubuntu-latest
    steps:
      - name: Get repository
        uses: actions/checkout@v4
      - name: Deploy
        uses: sebastianjnuwu/ssh-action-deploy@v4
        with:
          IP: ${{ secrets.HOST }}
          USER: ${{ secrets.USERNAME }}
          KEY: ${{ secrets.PASSWORD }}
          FOLDER: "/root/test"
          RUN: "ls -a; pwd"

    




