name: SSH deploy
on: push
jobs:
  deploy:
    name: Deploy project
    runs-on: ubuntu-latest
    steps:
      - name: Get repository
        uses: actions/checkout@v4
      - name: Deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script: |
            cd /root/test
            git pull origin main
            

    




